### PR TITLE
fixes #1

### LINKED ISSUE #1: Expand `dispatch` interface to support request other than http
This helps when other protocol such as websocket to pass-by.

### PR DESCRIPTION
**Pull request by weichensw**

### CODE REVIEW

**Comment by omsmith** [comment]
Is the errHandler because you'd provide a new one for use on the "upgrade" event?

I would also hesitate calling this an error handler, as it is simply a "default" or unmatched handler, yes?

Maybe we expose this as `.default(fn);`?

**Comment by omsmith** [comment]
It should be invalid to not have a default handler, so the check for `if(this._errHandler)` (or whatever new name) in the dispatcher is unnecessary

**Comment by weichensw** [comment]
the `dispatch` will call `handler(arguments)` since websocket will have 3 arguments (instead of `res` and `req`), this `errHandler` is called when there's no route matching, instead of `res.end()` directly, since in websocket, there's no `res` anymore.

So in a sense, it's a error (no route matched). The original behavior here is 404 and `res.end()`, which have the assumption of a http request.

**Comment by weichensw** [comment]
I agree the `if(this._errHandler)` is redundant now. Initially I didn't have a default for the `errHandler` so I have a `if` check when calling it. (i.e. I didn't `errHandler || function(){...}`) and later on I changed it into the current way. I will remove it.

**Comment by omsmith** [comment]
Not on my phone anymore so perhaps I can write a more detailed answer.

Don't think `errHandler` is a good name here. An error handler should just be another way of specifying `.on('error', listenerFn)` and stop the error events from being raised.

This would be better exposed as a _default_ handler. As that's the only "error" it handles.

For example:

``` js
PathRouter.prototype.default = function setDefaultHandler () {
  this._router.default.apply(this._router, arguments);
  return this;
}
```

``` js
function defaultHandler (req, res) { /* ... */ }

function Router () {
  // ...

 this._default = defaultHandler;
}

Router.prototype.default = function setDefaultHandler (fn) {
  if ('function' !== typeof fn) {
    throw new Error('"fn" must be a function');
  }

  this._default = fn;
}

Router.prototype.dispatch = function dispatch (req) {
  // ...

  this._default.apply(this, arguments);
}
```

If it doesn't matter to you - I could actually write that out and commit it with tests in place.

**Comment by omsmith** [comment]
I've got those changes in #3 which I'll merge once the tests pass.

I'll do the any-arity handler change after

**Comment by weichensw** [comment]
I see your point now. Yes I agree in this perspective it can be called `default` too.

I don't really mind the name, so long as the any-arity handler is there :)

Thanks for the help!

**Pull request closed without merging**
